Add support for custom fields
singer-io/tap-zendesk pull request #139
Opened 2023-07-24 09:23 UTC by Vi6hal

# Description of change
- Changelog & Version bump
- PR #124 

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2023-07-25 06:53 UTC, rdeshmukh15 approved these changes

2023-07-25 07:13 UTC, nitingaikwad1 approved these changes

2023-07-25 09:34 UTC, cosimon requested changes
Can you add the new field to the all_fields test?

2023-07-25 11:54 UTC, Vi6hal commented
> Can you add the new field to the all_fields test?

This is not exactly a new field, but rather a custom field type, and I have setup lookup fields on few streams to validate lookup datatype.

I was thinking to add a new test case for the following reason:
- This type of field is not available on the UI for selection (being a nested field) although the parent object is available for selection
- all_fields_test only covers the fields in the root hierarchy of the object and does not cover nested fields/schema
- the location of lookup fields varies for streams, hence its preferable to validate it separately. 

@cosimon what are your thoughts about adding a new test?

2023-07-25 14:05 UTC, lukas-gust commented
Let me know if I can be of any assistance.

2023-08-07 08:05 UTC, Vi6hal commented
> Let me know if I can be of any assistance.

I have made some changes as suggested, once the team reviews and approves this change, i will merge this P.R.

2023-08-07 11:25 UTC, RushiT0122 commented on test/unittests/test_customfield_schema_type.py
> +        z_field = self.get_z_field_obj("test_lookup_type","user_lookup_1","lookup")
```suggestion
        z_field = self.get_z_field_obj("test_lookup_type", "user_lookup_1", "lookup")
```

2023-08-07 11:29 UTC, RushiT0122 commented on tap_zendesk/streams.py
> +                    field.title, field.key, zendesk_type)
```suggestion
    if zendesk_type not in CUSTOM_TYPES:
        LOGGER.critical("Discovered unsupported type for custom field %s (key: %s): %s",
                        field.title, field.key, zendesk_type)
    json_type = CUSTOM_TYPES.get(zendesk_type) or "string"
```

2023-08-07 12:29 UTC, RushiT0122 commented on test/test_all_streams.py
> +
Remove extra line here and other similar locations.

2023-08-09 08:51 UTC, cosimon approved these changes

2023-08-09 10:26 UTC, RushiT0122 approved these changes

2023-08-09 12:17 UTC, merged